server:
  port: 8081

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/cvdb}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/cv-realm}

ollama:
  base-url: ${OLLAMA_BASE_URL:http://localhost:11434}
  embedding-model: ${OLLAMA_EMBEDDING_MODEL:embeddinggemma}

keycloak-admin:
  server-url: ${KEYCLOAK_SERVER_URL:http://localhost:8080}
  realm: ${KEYCLOAK_ADMIN_TARGET_REALM:cv-realm}
  auth-realm: ${KEYCLOAK_ADMIN_AUTH_REALM:master}
  client-id: ${KEYCLOAK_ADMIN_CLIENT_ID:admin-cli}
  client-secret: ${KEYCLOAK_ADMIN_CLIENT_SECRET:}
  username: ${KEYCLOAK_ADMIN_USERNAME:admin}
  password: ${KEYCLOAK_ADMIN_PASSWORD:admin123}

alfresco:
  base-url: ${ALFRESCO_BASE_URL:http://localhost:8082}
  username: ${ALFRESCO_USERNAME:admin}
  password: ${ALFRESCO_PASSWORD:admin}
  folder-id: ${ALFRESCO_FOLDER_ID:-shared-}
