services:
  kc-postgres:
    image: postgres:16
    container_name: kc-postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    ports:
      - "5433:5432"
    volumes:
      - kc_postgres_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:26.6.0
    container_name: keycloak
    command:
      - start-dev
      - --db=postgres
      - --db-url-host=kc-postgres
      - --db-url-database=keycloak
      - --db-username=keycloak
      - --db-password=keycloak
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin123
    ports:
      - "8080:8080"
    depends_on:
      - kc-postgres

  mongodb:
    image: mongodb/mongodb-community-server:8.0-ubuntu2204
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  kc_postgres_data:
  mongo_data: